### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by CherryLover** [li-yu/FakeWeather#1]
1. 在侧边栏打开的情况下，按下返回键整个应用程序自动退出。应该是当侧边栏处于打开的状态时，按下返回键，侧边栏关闭，再按一次返回键则退出应用程序。
2. 在权限中加入的了设置壁纸的权限，但是我没找到哪里有设置壁纸的入口。

**Comment by li-yu** [comment]
感谢反馈：
issue 1，稍晚点时候修复这个问题；
issue 2，在妹纸图的大图页面 action menu 里有设置壁纸的选项

**Comment by li-yu** [comment]
问题已修复，打开 App 检测更新即可，README 中下载链接也已同步更新。

**Comment by CherryLover** [comment]
我在打开妹子图的时候是全屏显示的，点击图片也不会出现toolbar必须使用返回键才能退出，但是使用返回键就退回到ViewPager界面了

**Comment by li-yu** [comment]
@CherryLover 打开妹子图时默认全屏显示，点击图片会**退出** or **进入**全屏模式。
如果你点击了图片无法显示 toolbar 和 statusbar 请告知手机型号和 OS 版本，我排查下，谢谢！

**Comment by CherryLover** [comment]
我的手机是HTC D626t Android 4.4.4
