### ISSUE TITLE
我发现一个视觉上的小问题

### ISSUE THREAD

**Issue by JadonPsycho** [li-yu/FakeWeather#3]
当在天气界面是 快速上划到底部 每周天气还没刷新 就会导致界面自动跳转到每周天气那边，（源码还没看）估计是RecyclerView或者是listView获得了焦点，我很喜欢这个天气界面，要学习一下 谢谢大神了

**Comment by li-yu** [comment]
@JadonPsycho 感谢反馈，我抽空完善下。哈哈，互相学习，共同进步！

**Comment by xcc3641** [comment]
项目完成度超高，好赞！
但是想提出一个小问题，为什么要隐藏状态栏呢？

**Comment by li-yu** [comment]
@xcc3641 :grinning: 竟然被三弟翻牌了。
隐藏状态栏纯粹是强迫症犯了，下个版本会去掉。

**Comment by xcc3641** [comment]
还以为因为开发时间不够适配沉浸式所以先隐藏处理了~
期待下个版本。

**Comment by li-yu** [comment]
@xcc3641 v1.3.1 已更新
