### ISSUE TITLE
720*1280 阴天效果出现问题

### ISSUE THREAD

**Issue by fingdo** [li-yu/FakeWeather#5]
<img width="450" alt="qq20180104-115652 2x" src="https://user-images.githubusercontent.com/24711451/34549790-614723a4-f146-11e7-8ccd-73c4f1043070.png">

**Comment by li-yu** [comment]
@fingdo 已确认该 bug，这两天会修复。

**Comment by li-yu** [comment]
@fingdo 已更新到 v1.3.1
