### ISSUE TITLE
我很遗憾

### ISSUE THREAD

**Issue by li-yu** [li-yu/FakeWeather#8]
最近几个月服务器流量大增，分析了接口数据，发现天气相关的几个接口请求量异常高，高出自动更新接口好几倍，得出了一个猜想：有人在用 api，数据量不小，应该发布在某个应用商店。
本着试试看的态度，去酷安上以“天气”为关键字，果然找到两个魔改 FakeWeather 的 app：
1. 一周天气预报  开发者：深圳市踏依依电子商务有限公司
2. 天天看天气   开发者：我是来挖宝的

FakeWeather 这个项目的初衷是学习研究，也没啥技术亮点，开源但也请遵照原创，对不起，我付费的服务器扛不住了，我很遗憾的关闭了天气相关的 api，相关 key   请自行申请吧。

**Comment by Leyiteyanzhi** [comment]
啊啊啊，手机一直在用，这两天用不了上来看看，原来关了啊，求大神教教怎么自己加上api，前端仔不会安卓，大神能帮忙下吗

**Comment by li-yu** [comment]
@Leyiteyanzhi 已经修复，打开 app 即可检测到更新或者下载 apk 自行安装

**Comment by leekaxi** [comment]
小尴尬，我被那个福利模块给吸引了，大佬你的妹子图是从哪里的服务器获取的

**Comment by li-yu** [comment]
@leekaxi 
一共有三个源：
http://gank.io
http://jandan.net
http://www.mzitu.com

**Comment by leekaxi** [comment]
@li-yu 谢谢大神，我好好研究一下

**Comment by NuonuoLabs** [comment]
请教下那个天气的动画，有什么可以参考的吗

**Comment by li-yu** [comment]
@1825492258 绘制动画的代码还是挺简单的，不知道你指的哪部分？

**Comment by ZhiHuangLin** [comment]
老哥，左右滑动切换城市要怎么实现

**Comment by ruanbaojun1105** [comment]
@ZhiHuangLin demo中不就是左右滑动城市的吗？
